version: "3"

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.18
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 5000:1883 # mqtt
      - 5001:9001 # websocket

  board:
    container_name: board
    build:
      context: board
      dockerfile: Dockerfile
    volumes:
      - ./board:/app
      - /app/node_modules
    ports:
      - 5003:3000
    depends_on:
      - mosquitto

  gamemaster:
    container_name: gamemaster
    build:
      context: gamemaster
      dockerfile: Dockerfile
    volumes:
      - ./gamemaster:/app
    ports:
      - 5002:8000
    environment:
      DJANGO_DATABASE_PASSWORD: postgres
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_USER: postgres
    depends_on:
      - mosquitto

  player:
    container_name: player
    build:
      context: player
      dockerfile: Dockerfile
    volumes:
      - ./player:/app
      - /app/node_modules
    ports:
      - 5005:3000
    depends_on:
      - mosquitto

  db:
    container_name: db
    image: postgres:16.1-alpine3.18
    ports:
      - 5004:5432
    volumes:
      - ./var/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  test-db:
    container_name: test-db
    image: postgres:16.1-alpine3.18
    ports:
      - 5010:5432
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 500000000
    command: postgres --fsync=off --synchronous-commit=off --full-page-writes=off
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
