# Generated by Django 4.2.7 on 2024-01-05 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='root_tile',
        ),
        migrations.AddField(
            model_name='tile',
            name='texture',
            field=models.FileField(blank=True, null=True, upload_to='textures', validators=[django.core.validators.FileExtensionValidator(['webp'])], verbose_name='Textur'),
        ),
    ]
