# Generated by Django 5.0.7 on 2024-08-06 07:43

import django.core.validators
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="action_context",
            field=models.JSONField(blank=True, default=dict, verbose_name="Aktionskontext"),
        ),
        migrations.AlterField(
            model_name="character",
            name="model",
            field=models.FileField(
                upload_to="characters",
                validators=[django.core.validators.FileExtensionValidator(["gltf"]), core.validators.validate_gltf],
                verbose_name="3D Modell",
            ),
        ),
    ]
