# Generated by Django 4.2.7 on 2024-01-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(verbose_name="Name")),
            ],
            options={
                "verbose_name": "Spielbrett",
                "verbose_name_plural": "Spielbretter",
            },
        ),
        migrations.AlterField(
            model_name="character",
            name="identifier",
            field=models.TextField(verbose_name="Identifier"),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Erstellt"),
                    ("RUNNING", "Läuft"),
                    ("PAUSED", "Pausiert"),
                    ("FINISHED", "Abgeschlossen"),
                    ("[('CREATED', 'Erstellt'), ('RUNNING', 'Läuft')]", "Accept Start Status"),
                ],
                default="CREATED",
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Tile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.TextField(verbose_name="Identifier")),
                ("type", models.TextField(choices=[("SIDE", "RAND"), ("CORNER", "Ecke")], verbose_name="Typ")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiles",
                        to="core.board",
                        verbose_name="Spielbrett",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessor",
                        to="core.tile",
                        verbose_name="Nachfolger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feld",
                "verbose_name_plural": "Felder",
            },
        ),
        migrations.AddField(
            model_name="board",
            name="root_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.tile", verbose_name="Startfeld"
            ),
        ),
    ]
