# Generated by Django 4.2.7 on 2024-01-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_board_root_tile_tile_texture"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="state",
            field=models.CharField(default="idle", verbose_name="Status"),
        ),
    ]
