# Generated by Django 4.2.7 on 2024-01-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_board_alter_character_identifier_alter_game_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="root_node",
        ),
        migrations.AddField(
            model_name="board",
            name="root_tile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.tile",
                verbose_name="Startfeld",
            ),
        ),
        migrations.AlterField(
            model_name="tile",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tiles",
                to="core.board",
                verbose_name="Spielbrett",
            ),
        ),
        migrations.AlterField(
            model_name="tile",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predecessor",
                to="core.tile",
                verbose_name="Nachfolger",
            ),
        ),
    ]
