from pathlib import Path

from django.core.files.uploadedfile import SimpleUploadedFile

from core.board.models import Board, Direction, Tile, TileTypes


def create():
    board, created = Board.objects.get_or_create(name="monopoly")

    with (Path(__file__).parent / "fixtures" / "texture.webp").open("rb") as texture_file:
        texture = SimpleUploadedFile("texture.webp", texture_file.read(), "image/webp")

    if not created:
        return board

    Tile.objects.create(
        board=board,
        identifier="start",
        type=TileTypes.CORNER,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="chur_kornplatz",
        type=TileTypes.SIDE,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="kanzlei2",
        type=TileTypes.SIDE,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="schaffhausen_vordergasse",
        type=TileTypes.SIDE,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="einkommenssteuer",
        type=TileTypes.SIDE,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="vereinigte_privatbahnen",
        type=TileTypes.SIDE,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="aarau_rathausplatz",
        type=TileTypes.SIDE,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="chance3",
        type=TileTypes.SIDE,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="neuenburg_place_pury",
        type=TileTypes.SIDE,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="thun_hauptgasse",
        type=TileTypes.SIDE,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="im_gefaengnis_nur_zu_besuch",
        type=TileTypes.CORNER,
        direction=Direction.LEFT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="basel_steinen_vorstadt",
        type=TileTypes.SIDE,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="elektrizitaetswerke",
        type=TileTypes.SIDE,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="solothurn_hauptgasse",
        type=TileTypes.SIDE,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="lugano_via_nassa",
        type=TileTypes.SIDE,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="vereinigte_bergbahnen_ag",
        type=TileTypes.SIDE,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="biel_nidaugasse",
        type=TileTypes.SIDE,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="kanzlei3",
        type=TileTypes.SIDE,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="freiburg_bahnhofstrasse",
        type=TileTypes.SIDE,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="la_chaux_de_fonds_avenue_l_robert",
        type=TileTypes.SIDE,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="freier_parkplatz",
        type=TileTypes.CORNER,
        direction=Direction.TOP,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="winterthur_bahnhofplatz",
        type=TileTypes.SIDE,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="chance1",
        type=TileTypes.SIDE,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="st_gallen_marktplatz",
        type=TileTypes.SIDE,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="bern_bundesplatz",
        type=TileTypes.SIDE,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="ueberlandbahnen",
        type=TileTypes.SIDE,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="luzern_weggisgasse",
        type=TileTypes.SIDE,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="zuerich_rennweg",
        type=TileTypes.SIDE,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="wasserwerke",
        type=TileTypes.SIDE,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="lausanne_rue_de_bourg",
        type=TileTypes.SIDE,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="gehe_ins_gefaengnis",
        type=TileTypes.CORNER,
        direction=Direction.RIGHT,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="basel_freie_strasse",
        type=TileTypes.SIDE,
        direction=Direction.BOTTOM,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="genf_rue_de_la_croix_dor",
        type=TileTypes.SIDE,
        direction=Direction.BOTTOM,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="kanzlei1",
        type=TileTypes.SIDE,
        direction=Direction.BOTTOM,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="bern_spitalgasse",
        type=TileTypes.SIDE,
        direction=Direction.BOTTOM,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="vereinigte_schwebebahnen_ag",
        type=TileTypes.SIDE,
        direction=Direction.BOTTOM,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="chance2",
        type=TileTypes.SIDE,
        direction=Direction.BOTTOM,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="lausanne_place_st_francois",
        type=TileTypes.SIDE,
        direction=Direction.BOTTOM,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="nachsteuer",
        type=TileTypes.SIDE,
        direction=Direction.BOTTOM,
        texture=texture,
    )
    Tile.objects.create(
        board=board,
        identifier="zuerich_paradeplatz",
        type=TileTypes.SIDE,
        direction=Direction.BOTTOM,
        texture=texture,
    )

    return board
