from core.board import BOTTOM, CORNER, LEFT, RIGHT, SIDE, TOP
from core.board.board import Board

monopoly = Board("start")

monopoly.add_node("start", type=CORNER)
monopoly.add_node("chur_kornplatz", type=SIDE)
monopoly.add_node("kanzlei2", type=SIDE)
monopoly.add_node("schaffhausen_vordergasse", type=SIDE)
monopoly.add_node("einkommenssteuer", type=SIDE)
monopoly.add_node("vereinigte_privatbahnen", type=SIDE)
monopoly.add_node("aarau_rathausplatz", type=SIDE)
monopoly.add_node("chance3", type=SIDE)
monopoly.add_node("neuenburg_place_pury", type=SIDE)
monopoly.add_node("thun_hauptgasse", type=SIDE)
monopoly.add_node("im_gefaengnis_nur_zu_besuch", type=CORNER)
monopoly.add_node("basel_steinen_vorstadt", type=SIDE)
monopoly.add_node("elektrizitaetswerke", type=SIDE)
monopoly.add_node("solothurn_hauptgasse", type=SIDE)
monopoly.add_node("lugano_via_nassa", type=SIDE)
monopoly.add_node("vereinigte_bergbahnen_ag", type=SIDE)
monopoly.add_node("biel_nidaugasse", type=SIDE)
monopoly.add_node("kanzlei3", type=SIDE)
monopoly.add_node("freiburg_bahnhofstrasse", type=SIDE)
monopoly.add_node("la_chaux_de_fonds_avenue_l_robert", type=SIDE)
monopoly.add_node("freier_parkplatz", type=CORNER)
monopoly.add_node("winterthur_bahnhofplatz", type=SIDE)
monopoly.add_node("chance1", type=SIDE)
monopoly.add_node("st_gallen_marktplatz", type=SIDE)
monopoly.add_node("bern_bundesplatz", type=SIDE)
monopoly.add_node("ueberlandbahnen", type=SIDE)
monopoly.add_node("luzern_weggisgasse", type=SIDE)
monopoly.add_node("zuerich_rennweg", type=SIDE)
monopoly.add_node("wasserwerke", type=SIDE)
monopoly.add_node("lausanne_rue_de_bourg", type=SIDE)
monopoly.add_node("gehe_ins_gefaengnis", type=CORNER)
monopoly.add_node("basel_freie_strasse", type=SIDE)
monopoly.add_node("genf_rue_de_la_croix_dor", type=SIDE)
monopoly.add_node("kanzlei1", type=SIDE)
monopoly.add_node("bern_spitalgasse", type=SIDE)
monopoly.add_node("vereinigte_schwebebahnen_ag", type=SIDE)
monopoly.add_node("chance2", type=SIDE)
monopoly.add_node("lausanne_place_st_francois", type=SIDE)
monopoly.add_node("nachsteuer", type=SIDE)
monopoly.add_node("zuerich_paradeplatz", type=SIDE)

monopoly.add_edge("start", "chur_kornplatz", direction=LEFT)
monopoly.add_edge("chur_kornplatz", "kanzlei2", direction=LEFT)
monopoly.add_edge("kanzlei2", "schaffhausen_vordergasse", direction=LEFT)
monopoly.add_edge("schaffhausen_vordergasse", "einkommenssteuer", direction=LEFT)
monopoly.add_edge("einkommenssteuer", "vereinigte_privatbahnen", direction=LEFT)
monopoly.add_edge("vereinigte_privatbahnen", "aarau_rathausplatz", direction=LEFT)
monopoly.add_edge("aarau_rathausplatz", "chance3", direction=LEFT)
monopoly.add_edge("chance3", "neuenburg_place_pury", direction=LEFT)
monopoly.add_edge("neuenburg_place_pury", "thun_hauptgasse", direction=LEFT)
monopoly.add_edge("thun_hauptgasse", "im_gefaengnis_nur_zu_besuch", direction=LEFT)
monopoly.add_edge(
    "im_gefaengnis_nur_zu_besuch", "basel_steinen_vorstadt", direction=TOP
)
monopoly.add_edge("basel_steinen_vorstadt", "elektrizitaetswerke", direction=TOP)
monopoly.add_edge("elektrizitaetswerke", "solothurn_hauptgasse", direction=TOP)
monopoly.add_edge("solothurn_hauptgasse", "lugano_via_nassa", direction=TOP)
monopoly.add_edge("lugano_via_nassa", "vereinigte_bergbahnen_ag", direction=TOP)
monopoly.add_edge("vereinigte_bergbahnen_ag", "biel_nidaugasse", direction=TOP)
monopoly.add_edge("biel_nidaugasse", "kanzlei3", direction=TOP)
monopoly.add_edge("kanzlei3", "freiburg_bahnhofstrasse", direction=TOP)
monopoly.add_edge(
    "freiburg_bahnhofstrasse", "la_chaux_de_fonds_avenue_l_robert", direction=TOP
)
monopoly.add_edge(
    "la_chaux_de_fonds_avenue_l_robert", "freier_parkplatz", direction=TOP
)
monopoly.add_edge("freier_parkplatz", "winterthur_bahnhofplatz", direction=RIGHT)
monopoly.add_edge("winterthur_bahnhofplatz", "chance1", direction=RIGHT)
monopoly.add_edge("chance1", "st_gallen_marktplatz", direction=RIGHT)
monopoly.add_edge("st_gallen_marktplatz", "bern_bundesplatz", direction=RIGHT)
monopoly.add_edge("bern_bundesplatz", "ueberlandbahnen", direction=RIGHT)
monopoly.add_edge("ueberlandbahnen", "luzern_weggisgasse", direction=RIGHT)
monopoly.add_edge("luzern_weggisgasse", "zuerich_rennweg", direction=RIGHT)
monopoly.add_edge("zuerich_rennweg", "wasserwerke", direction=RIGHT)
monopoly.add_edge("wasserwerke", "lausanne_rue_de_bourg", direction=RIGHT)
monopoly.add_edge("lausanne_rue_de_bourg", "gehe_ins_gefaengnis", direction=RIGHT)
monopoly.add_edge("gehe_ins_gefaengnis", "basel_freie_strasse", direction=BOTTOM)
monopoly.add_edge("basel_freie_strasse", "genf_rue_de_la_croix_dor", direction=BOTTOM)
monopoly.add_edge("genf_rue_de_la_croix_dor", "kanzlei1", direction=BOTTOM)
monopoly.add_edge("kanzlei1", "bern_spitalgasse", direction=BOTTOM)
monopoly.add_edge("bern_spitalgasse", "vereinigte_schwebebahnen_ag", direction=BOTTOM)
monopoly.add_edge("vereinigte_schwebebahnen_ag", "chance2", direction=BOTTOM)
monopoly.add_edge("chance2", "lausanne_place_st_francois", direction=BOTTOM)
monopoly.add_edge("lausanne_place_st_francois", "nachsteuer", direction=BOTTOM)
monopoly.add_edge("nachsteuer", "zuerich_paradeplatz", direction=BOTTOM)
monopoly.add_edge("zuerich_paradeplatz", "start", direction=BOTTOM)
