# Generated by Django 3.1.6 on 2021-03-07 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tile_groups', to='game.board')),
            ],
            options={
                'verbose_name': 'Tilegroup',
                'verbose_name_plural': 'Tilegroups',
            },
        ),
    ]
