# Generated by Django 3.1.6 on 2021-03-07 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_tilegroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("title", models.CharField(max_length=4096, verbose_name="Feldtitel")),
                (
                    "tile_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="tiles", to="game.tilegroup"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tile",
                "verbose_name_plural": "Tiles",
            },
        ),
    ]
