# Generated by Django 3.1.6 on 2021-03-07 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_tile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='figure', to=settings.AUTH_USER_MODEL)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='figures', to='game.tile')),
            ],
            options={
                'verbose_name': 'Figure',
                'verbose_name_plural': 'Figures',
            },
        ),
    ]
