# Generated by Django 3.1.6 on 2021-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_figure"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="is_corner",
            field=models.BooleanField(default=False, verbose_name="Ist Ecke"),
        ),
    ]
