# Generated by Django 3.1.6 on 2021-03-07 12:39

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("game", "0005_tile_is_corner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChancelleryTile",
            fields=[
                (
                    "tile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.tile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chancellery Tile",
                "verbose_name_plural": "Chancellery Tiles",
            },
            bases=("game.tile",),
        ),
        migrations.CreateModel(
            name="ChanceTile",
            fields=[
                (
                    "tile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.tile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chance Tile",
                "verbose_name_plural": "Chance Tiles",
            },
            bases=("game.tile",),
        ),
        migrations.CreateModel(
            name="ColoredTile",
            fields=[
                (
                    "tile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.tile",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FF0000", max_length=18, verbose_name="Color"),
                ),
                ("subtitle", models.CharField(max_length=4096, null=True, verbose_name="Fieldsubtitle")),
            ],
            options={
                "verbose_name": "Tile",
                "verbose_name_plural": "Tiles",
            },
            bases=("game.tile",),
        ),
        migrations.CreateModel(
            name="SimpleTile",
            fields=[
                (
                    "tile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.tile",
                    ),
                ),
                ("subtitle", models.CharField(max_length=4096, null=True, verbose_name="Fieldsubtitle")),
            ],
            options={
                "verbose_name": "Tile",
                "verbose_name_plural": "Tiles",
            },
            bases=("game.tile",),
        ),
        migrations.AlterModelOptions(
            name="tile",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="tile",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_game.tile_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="tile",
            name="is_corner",
            field=models.BooleanField(default=False, verbose_name="Is a corner"),
        ),
        migrations.AlterField(
            model_name="tile",
            name="title",
            field=models.CharField(max_length=4096, null=True, verbose_name="Fieldtitle"),
        ),
    ]
