ATTACH_TO = {
    "RIGHT": "right",
    "BOTTOM": "bottom",
    "LEFT": "left",
    "TOP": "top",
}


monopoly = [
    [0, ATTACH_TO["TOP"], "parking"],
    [1, ATTACH_TO["RIGHT"], "wasserwerk"],
    [1, ATTACH_TO["RIGHT"], "wasserwerk"],
    [1, ATTACH_TO["RIGHT"], "wasserwerk"],
    [1, ATTACH_TO["RIGHT"], "wasserwerk"],
    [1, ATTACH_TO["RIGHT"], "wasserwerk"],
    [1, ATTACH_TO["RIGHT"], "wasserwerk"],
    [1, ATTACH_TO["RIGHT"], "wasserwerk"],
    [1, ATTACH_TO["RIGHT"], "wasserwerk"],
    [1, ATTACH_TO["RIGHT"], "wasserwerk"],
    [0, ATTACH_TO["RIGHT"], "police"],
    [1, ATTACH_TO["BOTTOM"], "luzern"],
    [1, ATTACH_TO["BOTTOM"], "luzern"],
    [1, ATTACH_TO["BOTTOM"], "luzern"],
    [1, ATTACH_TO["BOTTOM"], "luzern"],
    [1, ATTACH_TO["BOTTOM"], "luzern"],
    [1, ATTACH_TO["BOTTOM"], "luzern"],
    [1, ATTACH_TO["BOTTOM"], "luzern"],
    [1, ATTACH_TO["BOTTOM"], "luzern"],
    [1, ATTACH_TO["BOTTOM"], "luzern"],
    [0, ATTACH_TO["BOTTOM"], "start"],
    [1, ATTACH_TO["LEFT"], "elektrizitaetswerk"],
    [1, ATTACH_TO["LEFT"], "elektrizitaetswerk"],
    [1, ATTACH_TO["LEFT"], "elektrizitaetswerk"],
    [1, ATTACH_TO["LEFT"], "elektrizitaetswerk"],
    [1, ATTACH_TO["LEFT"], "elektrizitaetswerk"],
    [1, ATTACH_TO["LEFT"], "elektrizitaetswerk"],
    [1, ATTACH_TO["LEFT"], "elektrizitaetswerk"],
    [1, ATTACH_TO["LEFT"], "elektrizitaetswerk"],
    [1, ATTACH_TO["LEFT"], "elektrizitaetswerk"],
    [0, ATTACH_TO["LEFT"], "jail"],
    [1, ATTACH_TO["TOP"], "basel_steinenvorstadt"],
    [1, ATTACH_TO["TOP"], "basel_steinenvorstadt"],
    [1, ATTACH_TO["TOP"], "basel_steinenvorstadt"],
    [1, ATTACH_TO["TOP"], "basel_steinenvorstadt"],
    [1, ATTACH_TO["TOP"], "basel_steinenvorstadt"],
    [1, ATTACH_TO["TOP"], "basel_steinenvorstadt"],
    [1, ATTACH_TO["TOP"], "basel_steinenvorstadt"],
    [1, ATTACH_TO["TOP"], "basel_steinenvorstadt"],
    [1, ATTACH_TO["TOP"], "basel_steinenvorstadt"],
]
